[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
simple_solana_game = "463GgDpBgQDQ68CwEth4bAFpYmFS79vkpoQ61YBTG1pj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/elcomandante/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
